# Generated by Django 2.0.3 on 2018-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['nutrition_grade', 'nutrition_score'], 'verbose_name': 'aliment'},
        ),
    ]
