# Generated by Django 2.0.3 on 2018-05-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180516_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'aliment'},
        ),
    ]
